export function getRandomQuote(): string {
  let index = Math.floor(Math.random() * quotes.length);
  index = Math.min(index, quotes.length - 1);
  return quotes[index];
}

const quotes = [
  "Dream big, work hard, and never give up.",
  "Stay humble, hustle hard, and trust the process.",
  "Progress over perfection, always keep moving.",
  "Keep going, keep growing, and keep believing.",
  "Do more, worry less, and enjoy the journey.",
  "Rise up, stay strong, and push forward.",
  "No risk, no reward, so take the leap.",
  "Work hard, stay kind, and inspire others.",
  "Less doubt, more action, and watch success follow.",
  "Stronger than yesterday, braver than ever.",
  "Mistakes are lessons, growth is the reward.",
  "Small steps lead to big results over time.",
  "Grow through what you go through, always learn.",
  "Learn, adapt, evolve, and keep improving.",
  "Action beats intention, so take the first step.",
  "Create, innovate, inspire, and change the world.",
  "One step at a time, one goal at a time.",
  "Fail fast, learn faster, and keep going.",
  "Success loves preparation, so always be ready.",
  "Believe, achieve, succeed, and repeat daily.",
  "Effort equals progress, and progress equals success.",
  "Push harder, shine brighter, and stand out.",
  "Start now, not later, and make it count.",
  "Your pace, your race, run it your way.",
  "Mindset is everything, so think positively.",
  "Failure fuels growth, and growth fuels success.",
  "Focus on the solution, not the problem.",
  "Learn daily, grow endlessly, and keep evolving.",
  "Be fearless, be limitless, and chase your dreams.",
  "Win or learn, never lose, always move forward.",
  "Your limits are mental, break through them.",
  "Stay patient, stay focused, and trust the timing.",
  "Create your own luck through hard work.",
  "Act with purpose, passion, and perseverance.",
  "Make it happen, don't wait for it to happen.",
  "Excuses change nothing, actions change everything.",
  "Fear is temporary, regret lasts forever.",
  "Master your mindset, master your destiny.",
  "No challenge, no growth, embrace the struggle.",
  "Turn obstacles into opportunities and thrive.",
  "Stay hungry, stay foolish, and stay persistent.",
  "Dreams require action, so start now.",
  "Success starts with belief and hard work.",
  "Discipline drives success, not just motivation.",
  "Strive for progress, not overnight perfection.",
  "Hard work beats talent when talent is lazy.",
  "Trust the process, even when it's slow.",
  "Commit to the journey, not just the goal.",
  "Doubt kills more dreams than failure ever will.",
  "Think big, start small, and keep going.",
  "Turn pain into power and rise above.",
  "Embrace the grind, enjoy the results.",
  "Push past limits and redefine possible.",
  "Your growth is your responsibility, own it.",
  "Chase excellence, not just success.",
  "No shortcuts to success, only hard work.",
  "Work smart, stay consistent, and be patient.",
  "Lead by example and inspire those around you.",
  "Success is earned through dedication and effort.",
  "Courage over comfort, always push yourself.",
  "Failure is not the end, just a lesson.",
  "Make every second count towards your dreams.",
  "Struggle builds strength, so embrace the challenge.",
  "Take action, get results, and never stop.",
  "Small wins build momentum, celebrate them.",
  "Be your own hero, no one will do it for you.",
  "Stay consistent, stay unstoppable, and stay focused.",
  "Dreams demand dedication, discipline, and patience.",
  "Fear less, do more, and take bold steps.",
  "Decide, commit, succeed, and stay on track.",
  "Your time is now, don't waste it.",
  "Step out of your comfort zone and grow.",
  "Progress requires effort, not just wishes.",
  "Focus, execute, succeed, and repeat daily.",
  "Master the basics before chasing the complex.",
  "Hustle with heart and passion every day.",
  "Make today count, because tomorrow isn't promised.",
  "Turn dreams into reality with determination.",
  "Failure is a stepping stone, not a dead end.",
  "Consistency beats intensity, so keep at it.",
  "Your actions define you, not just your words.",
  "Every day is a fresh start, use it well.",
  "Winners never quit, and quitters never win.",
  "Take the first step, and doors will open.",
  "Never stop learning, growing, and improving.",
  "Every setback is a setup for a comeback.",
  "Create, don't wait, and make opportunities.",
  "Stay focused, stay fearless, and chase greatness.",
  "Break barriers, build dreams, and reach higher.",
  "Your mindset shapes your world, so think big.",
  "Be the change you seek in the world.",
  "Opportunities don't wait, so take action now.",
  "Embrace the struggle, it makes you stronger.",
  "Growth begins at discomfort, push through it.",
  "Push through the pain, and find your power.",
  "Stay dedicated, stay disciplined, and stay driven.",
  "Believe in your grind, and trust yourself.",
  "Be unstoppable, nothing can hold you back.",
];
