FROM debian:12.7

# Declare ARG to make it available in the RUN commands
ARG TARGETPLATFORM
RUN echo "Building for ${TARGETPLATFORM}"
RUN if [ "${TARGETPLATFORM}" != "linux/amd64" ] && [ "${TARGETPLATFORM}" != "linux/arm64" ]; then \
        echo "Unsupported architecture: ${TARGETPLATFORM}" && \
        exit 1; \
    fi

# Set the general environment variables, and move to temp dir
ENV DEBIAN_FRONTEND="noninteractive"
RUN mkdir -p /app/temp
WORKDIR /app/temp

# Install debian packages
RUN apt update && \
    apt install -y \
        wget zip unzip p7zip-full tzdata git ffmpeg npm python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install Node.js
RUN npm install --global n@latest && \
    n v22

# Go to the app dir, delete the temporary dir and create backups dir
WORKDIR /app
RUN rm -rf /app/temp

##############
# START HERE #
##############

# Add the startup script on every bash session
COPY scripts/startup.sh /usr/local/bin/startup.sh
RUN echo "\n\n" >> /root/.bashrc && \
    cat /usr/local/bin/startup.sh >> /root/.bashrc

# Command just to keep the container running
CMD ["sleep", "infinity"]
